/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IgestionIndicadores.h"
#include "IgestionNotificaciones.h"

void *
enviarindicador_1_svc(int *argp, struct svc_req *rqstp)
{

	CLIENT *clnt;
	void  *result_1;
	int  enviarnotificacion_1_arg;

#ifndef	DEBUG
	char *host="localhost";
	clnt = clnt_create (host, GESPROGRAM2, GESVER2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	static char * result;

	printf("Desde enviarindicador()...\n");
	printf("Indicador recibido: %d\n",*argp);
	if(*argp>50){
		printf("indicador fuera de rago\n");
		printf("Enviando notificacion():%d\n",*argp);
		printf("Invocando enviarnotificacion()...\n");
		enviarnotificacion_1_arg=*argp;
		result_1 = enviarnotificacion_1(&enviarnotificacion_1_arg, clnt);
		if (result_1 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}else{
		printf("indicador normal\n");
	}

	return (void *) &result;
}
