/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "division.h"

float *
operar_division_1_svc(num *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("*** Division *** \n");
	result = argp->a / argp->b;

	return &result;
}
