/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	float a;
	float b;
};
typedef struct numbers numbers;

#define calculadora 0x20000001
#define calculadora_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  float * suma_1(numbers *, CLIENT *);
extern  float * suma_1_svc(numbers *, struct svc_req *);
#define resta 2
extern  float * resta_1(numbers *, CLIENT *);
extern  float * resta_1_svc(numbers *, struct svc_req *);
#define multiplicacion 3
extern  float * multiplicacion_1(numbers *, CLIENT *);
extern  float * multiplicacion_1_svc(numbers *, struct svc_req *);
#define division 4
extern  float * division_1(numbers *, CLIENT *);
extern  float * division_1_svc(numbers *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define resta 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define multiplicacion 3
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define division 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
