/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
suma_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("\n*** Invocando a suma ***\n");
	result = argp->a + argp->b;

	return &result;
}

float *
resta_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;
	
	printf("\n*** Invocando a resta ***\n");
	result = argp->a - argp->b;

	return &result;
}

float *
multiplicacion_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("\n*** Invocando a multiplicacion ***\n");
	result = argp->a * argp->b;

	return &result;
}

float *
division_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("\n*** Invocando a division ***\n");
	result = argp->a / argp->b;

	return &result;
}
