/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IGESTIONINDICADORES_H_RPCGEN
#define _IGESTIONINDICADORES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define GES1PROGRAM 0x20000001
#define GES1VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define enviarIndicador 1
extern  void * enviarindicador_1(int *, CLIENT *);
extern  void * enviarindicador_1_svc(int *, struct svc_req *);
extern int ges1program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarIndicador 1
extern  void * enviarindicador_1();
extern  void * enviarindicador_1_svc();
extern int ges1program_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IGESTIONINDICADORES_H_RPCGEN */
