/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionUsuarios.h"

datos_usuario vectorUsuarios[6];
int posUsuarios=1;

datos_usuario *
abrirsesion_1_svc(datos_sesion *argp, struct svc_req *rqstp)
{
	static datos_usuario  result;

    vectorUsuarios[0].id = 0;
    strcpy(vectorUsuarios[0].nombreCompleto, "Administrador");
    vectorUsuarios[0].edad = 0;
    strcpy(vectorUsuarios[0].usuario, "admin");
    strcpy(vectorUsuarios[0].clave, "admin");
	int i, bandera = 0;
	

	printf("\n Servidor: Iniciar sesion\n");
	if((argp->id == vectorUsuarios[0].id) && strcmp(argp->usuario, vectorUsuarios[0].usuario) == 0 && strcmp(argp->clave, vectorUsuarios[0].clave) == 0)
	{
		result.id = 0;
		printf("\n Servidor: Sesion iniciada Admin\n");
		return &result;
    }
	
	for (i = 0; i < 5; i++)
	{
		if(argp->id == vectorUsuarios[i].id)
		{
			result = vectorUsuarios[i];
			printf("\n Servidor: Sesion iniciada jugador %d\n",vectorUsuarios[i].id);
			result.id = vectorUsuarios[i].id;
			bandera = 1;
			break;
		}	
	}
	if(bandera == 0)
	{
		printf("\n Servidor: Usuario no encontrado\n");
		result.id = -1;
	}
	

	return &result;
}

bool_t *
registrarusuarios_1_svc(datos_usuario *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n Servidor: Registrar usuarios\n");
	if(posUsuarios < 5)
	{
		vectorUsuarios[posUsuarios]=*argp;
		posUsuarios++;
		printf("\n Servidor: Usuario registrado\n");
		result = TRUE;
	}
	else
	{
		printf("\n Servidor: Cantidad maxima de usuarios alcanzada\n");
		result = FALSE;
	}

	return &result;
}

datos_usuario *
consultarusuario_1_svc(int *argp, struct svc_req *rqstp)
{
	static datos_usuario  result;

	printf("\n Servidor: Consultar usuario\n");
	int i, bandera;
	bandera = 0;
	for(i = 0; i < 5; i++)
	{
		if(*argp == vectorUsuarios[i].id)
		{
			result = vectorUsuarios[i];
			bandera = 1;
			printf("\n Servidor: Usuario encontrado\n");
			break;
		}
	}
	if(bandera == 0)
	{
		printf("Servidor: El usuario con id %d no se encuentra registrado\n", *argp);
		result.id = -1;
	}

	return &result;
}
