/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "./gestionAnteproyectos.h"

bool_t
xdr_nodo_anteproyecto (XDR *xdrs, nodo_anteproyecto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->estudiante, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fechaPresentacion, MAXFECHA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->codigo))
		 return FALSE;
	return TRUE;
}
