/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionAnteproyectos.h"

nodo_anteproyecto vectorAnteproyectos[5];
int posAnteproyectos=0;
bool_t *
registraranteproyectosistema_1_svc(nodo_anteproyecto *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\n Invocando a registrar anteproyecto");
	if(posAnteproyectos < 4)
	{
		vectorAnteproyectos[posAnteproyectos]=*argp;
		posAnteproyectos++;
		printf("\n Anteproyecto registrado");
		result = TRUE;
	}
	else
	{
		printf("\n Cantidad maxima de anteproyectos");
		result = FALSE;
	}
	return &result;
}

nodo_anteproyecto *
consultaranteproyecto_1_svc(char **argp, struct svc_req *rqstp)
{
	static nodo_anteproyecto  result;
	printf("\n Invocando a consultar anteproyecto");
	int i, bandera;
	bandera = 0;
	for(i = 0; i < 5; i++)
	{
		
		if(strcmp(*argp, vectorAnteproyectos[i].titulo) == 0)
		{
			
			result = vectorAnteproyectos[i];
			bandera = 1;
			break;
		}
	}
	if(bandera == 0)
	{
		printf("El anteproyecto con titulo %s no se encuentra registrado\n", *argp);
		result.codigo = -1;
	}
	return &result;
}
