/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calculator_result (XDR *xdrs, calculator_result *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->state))
		 return FALSE;
	return TRUE;
}
