/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "multioperaciones.h"


void
multioperaciones_1(char *host)
{
	CLIENT *clnt;
	nodo_multioperaciones  *result_1;
	numbers  operar_1_arg;
	int op = 0;

#ifndef	DEBUG
	clnt = clnt_create (host, multioperaciones, multioperaciones_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	do
	{
		printf("Ingrese el primer numero: ");
		scanf("%f", &operar_1_arg.a);
		printf("Ingrese el segundo numero: ");
		scanf("%f", &operar_1_arg.b);
		result_1 = operar_1(&operar_1_arg, clnt);
		if (result_1 == (nodo_multioperaciones *) NULL) {
		clnt_perror (clnt, "call failed");
		}
		else
		{
			printf("Estado: %s\n", result_1->estado);
			if (strcmp(result_1->estado, "Error") != 0)
			{
				printf("El resultado de la operacion es: %s\n", result_1->resultado);
			}		
			printf("Desea realizar otra operacion? (1=si, 0=no): ");
			scanf("%d", &op);		
		}
	} while (op == 0);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	multioperaciones_1 (host);
exit (0);
}
