/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	float a;
	float b;
};
typedef struct numbers numbers;

struct calculator_result {
	float result;
	bool_t state;
};
typedef struct calculator_result calculator_result;

#define calculadora 0x20000001
#define calculadora_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  calculator_result * suma_1(numbers *, CLIENT *);
extern  calculator_result * suma_1_svc(numbers *, struct svc_req *);
#define resta 2
extern  calculator_result * resta_1(numbers *, CLIENT *);
extern  calculator_result * resta_1_svc(numbers *, struct svc_req *);
#define multiplicacion 3
extern  calculator_result * multiplicacion_1(numbers *, CLIENT *);
extern  calculator_result * multiplicacion_1_svc(numbers *, struct svc_req *);
#define division 4
extern  calculator_result * division_1(numbers *, CLIENT *);
extern  calculator_result * division_1_svc(numbers *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  calculator_result * suma_1();
extern  calculator_result * suma_1_svc();
#define resta 2
extern  calculator_result * resta_1();
extern  calculator_result * resta_1_svc();
#define multiplicacion 3
extern  calculator_result * multiplicacion_1();
extern  calculator_result * multiplicacion_1_svc();
#define division 4
extern  calculator_result * division_1();
extern  calculator_result * division_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);
extern  bool_t xdr_calculator_result (XDR *, calculator_result*);

#else /* K&R C */
extern bool_t xdr_numbers ();
extern bool_t xdr_calculator_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
