/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

calculator_result *
suma_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static calculator_result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

calculator_result *
resta_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static calculator_result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

calculator_result *
multiplicacion_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static calculator_result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

calculator_result *
division_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static calculator_result  result;

	/*
	 * insert server code here
	 */

	return &result;
}
