/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionJuego.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestion_juego_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int iniciarjuego_1_arg;
		config_juego enviarconfiguracion_1_arg;
		info_color enviarcolores_1_arg;
		int actualizartablerocolor_1_arg;
		info_espiga enviarespigas_1_arg;
		int actualizartableroespiga_1_arg;
		int puntuacion_1_arg;
		int enviarconfirmacion_1_arg;
		int consulta_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case iniciarJuego:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) iniciarjuego_1_svc;
		break;

	case enviarconfiguracion:
		_xdr_argument = (xdrproc_t) xdr_config_juego;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) enviarconfiguracion_1_svc;
		break;

	case configuracion:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_config_juego;
		local = (char *(*)(char *, struct svc_req *)) configuracion_1_svc;
		break;

	case enviarColores:
		_xdr_argument = (xdrproc_t) xdr_info_color;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) enviarcolores_1_svc;
		break;

	case actualizarTableroColor:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_info_color;
		local = (char *(*)(char *, struct svc_req *)) actualizartablerocolor_1_svc;
		break;

	case enviarEspigas:
		_xdr_argument = (xdrproc_t) xdr_info_espiga;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) enviarespigas_1_svc;
		break;

	case actualizarTableroEspiga:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_info_espiga;
		local = (char *(*)(char *, struct svc_req *)) actualizartableroespiga_1_svc;
		break;

	case puntuacion:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_fin_juego;
		local = (char *(*)(char *, struct svc_req *)) puntuacion_1_svc;
		break;

	case enviarConfirmacion:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) enviarconfirmacion_1_svc;
		break;

	case estadoJuego:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) estadojuego_1_svc;
		break;

	case consulta:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_data_juego;
		local = (char *(*)(char *, struct svc_req *)) consulta_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (gestion_juego, gestion_juego_version);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_juego, gestion_juego_version, gestion_juego_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_juego, gestion_juego_version, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_juego, gestion_juego_version, gestion_juego_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_juego, gestion_juego_version, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
