/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionJuego.h"

int *
iniciarjuego_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
enviarconfiguracion_1_svc(config_juego *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

config_juego *
configuracion_1_svc(void *argp, struct svc_req *rqstp)
{
	static config_juego  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
enviarcolores_1_svc(info_color *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

info_color *
actualizartablerocolor_1_svc(int *argp, struct svc_req *rqstp)
{
	static info_color  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
enviarespigas_1_svc(info_espiga *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

info_espiga *
actualizartableroespiga_1_svc(int *argp, struct svc_req *rqstp)
{
	static info_espiga  result;

	/*
	 * insert server code here
	 */

	return &result;
}

fin_juego *
puntuacion_1_svc(int *argp, struct svc_req *rqstp)
{
	static fin_juego  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
enviarconfirmacion_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

int *
estadojuego_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

data_juego *
consulta_1_svc(int *argp, struct svc_req *rqstp)
{
	static data_juego  result;

	/*
	 * insert server code here
	 */

	return &result;
}
