/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionJuego.h"
#include "registroJuego.h"

int contador = 0;

void *
iniciarjuego_1_svc(int *argp, struct svc_req *rqstp)
{
	CLIENT *clnt;
	void  *result_1;
	struct datos_juego  enviarnotificacion_1_arg;

#ifndef	DEBUG
	char *host="localhost";
	clnt = clnt_create (host, registro_juego, registro_juego_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	static char * result;

	// contar los usuarios que llegan
	// si son 2, iniciar el juego
	printf("*** Juego Iniciado ***\n");
	contador = contador + 1;

	if (contador == 1)
	{		
		//Guardar el id del jugador 1
		printf("*** Jugador 1: %d ***\n", *argp);
		enviarnotificacion_1_arg.id_jugador1 = *argp;
		
	}else
	{
		//Verificar que no sea el mismo jugador
		if (*argp == enviarnotificacion_1_arg.id_jugador1)
		{
			printf("*** Jugador 1 y Jugador 2 son el mismo ***\n");
			result = "Jugador 1 y Jugador 2 son el mismo";
			return (void *) &result;
		}
		//Guardar el id del jugador 2
		printf("*** Jugador 2: %d ***\n", *argp);
		enviarnotificacion_1_arg.id_jugador2 = *argp;

		//Guardar el id del juego
		enviarnotificacion_1_arg.id_juego = contador;

		//Enviar notificacion a los jugadores
		result_1 = enviarnotificacion_1(&enviarnotificacion_1_arg, clnt);
		if (result_1 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("*** hay 2 jugadores, enviar notificacion ***\n");
	}
	
	return (void *) &result;
}


