/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionUsuarios.h"
#include "gestionJuego.h"
#include <unistd.h>

//declaramos una matriz de caracteres para los colores
char matriz[10][10][15];
void listaColores();
int obtenerNumeroValido(int rango);
char* obtenerColor(int numero);
char* obtenerEspiga(int numero);
void tablero(int generacionColor, int generacionEspiga);
void escudo();
void reiniciar();


//Estructura para guardar los colores
struct data_color
{
	char color1[JMAXDAT];
    char color2[JMAXDAT];
    char color3[JMAXDAT];
    char color4[JMAXDAT];
    char color5[JMAXDAT];
};

//Estructura de colores para adivinar
struct solucion_color
{
	char color1[JMAXDAT];
    char color2[JMAXDAT];
    char color3[JMAXDAT];
    char color4[JMAXDAT];
    char color5[JMAXDAT];
};

//Estructura para guardar las espigas
struct data_espiga
{
	char espiga1[JMAXDAT];
	char espiga2[JMAXDAT];
	char espiga3[JMAXDAT];
	char espiga4[JMAXDAT];
	char espiga5[JMAXDAT];
};

struct data_color color;
struct data_espiga espiga;
struct solucion_color solucion;



void
gestion_usuarios_1(char *host)
{
	CLIENT *clnt;
	datos_usuario  *result_1;
	datos_sesion  abrirsesion_1_arg;
	bool_t  *result_2;
	datos_usuario  registrarusuarios_1_arg;
	datos_usuario  *result_3;
	int  consultarusuario_1_arg;
	int generacionColor = 1;
	int generacionEspiga = 0;
	int repetirColor;
	int repetirColor2;
	int partida = 0;



#ifndef	DEBUG
	clnt = clnt_create (host, gestion_usuarios, gestion_usuarios_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int opcion3;
	int opcion2;
	int opcion;
	do
	{
		printf("\n================ Menu sesion ==================");
		printf("\n 1. Iniciar sesion ");
		printf("\n 2. Salir ");
		printf("\n=======================================");
		printf("\n Digite opcion: ");
		scanf("%d",&opcion);
		switch(opcion)
		{    
			case 1:
				printf("\n----------------");
				printf(" Iniciar sesion");
				printf(" -----------------\n");

				printf("Digite el numero de identificacion: ");
				scanf("%d",&abrirsesion_1_arg.id);
				printf("Digite su usuario: ");
				scanf("%s", &abrirsesion_1_arg.usuario);
				printf("Digite su clave: ");
				scanf("%s", &abrirsesion_1_arg.clave);

				result_1=abrirsesion_1(&abrirsesion_1_arg,clnt);
				if ((*result_1).id == -1) {
					printf("\nUsuario NO encontrado");
				}
				else{

					if ((*result_1).id > 0)
					{
						CLIENT *clnt1;
						int  *result_4;
						int  iniciarjuego_1_arg;
						void  *result_5;
						config_juego  enviarconfiguracion_1_arg;
						config_juego  *result_6;
						char *configuracion_1_arg;
						bool_t  *result_7;
						info_color  enviarcolores_1_arg;
						info_color  *result_8;
						int  actualizartablerocolor_1_arg;
						bool_t  *result_9;
						info_espiga  enviarespigas_1_arg;
						info_espiga  *result_10;
						int  actualizartableroespiga_1_arg;
						fin_juego  *result_11;
						int  puntuacion_1_arg;
						void  *result_12;
						int  enviarconfirmacion_1_arg;
						int  *result_13;
						char *estadojuego_1_arg;
						data_juego  *result_14;
						int  consulta_1_arg;
						


						#ifndef	DEBUG
							clnt1 = clnt_create (host, gestion_juego, gestion_juego_version, "udp");
							if (clnt1 == NULL) {
								clnt_pcreateerror (host);
								exit (1);
							} 
						#endif	/* DEBUG  */

						do{

							printf("\n================ Menu Jugador ==================");
							printf("\n 1. Jugar");
							printf("\n 2. Consultar Registro");
							printf("\n 3. Salir ");
							printf("\n================================================");
							printf("\n Digite opcion: ");
							scanf("%d",&opcion3);
							switch(opcion3)
							{    
								case 1:
									//Configurar juego
									printf("\n----------------");
									printf(" Configurar juego");
									printf(" -----------------\n");
									//preguntar si ya esta configurado al servidor

									result_6 = configuracion_1((void*)&configuracion_1_arg, clnt1);
									if (result_6 == (config_juego *) NULL) {
										clnt_perror (clnt1, "call failed");
									}
									
									if (result_6->id_partida == 0)
									{										

										printf("\nDigite el rol que desea jugar:  1 = Mastermind |  2 = Espiga \n");
										scanf("%d",&enviarconfiguracion_1_arg.rol);

										// Validamos si se repite color
										enviarconfiguracion_1_arg.repetirColor = 1;

										printf("\n¿Desea repetir color? 1:si / 0:no \n");
										scanf(" %d", &repetirColor);

										enviarconfiguracion_1_arg.repetirColor = repetirColor;

										//inicio del juego
										iniciarjuego_1_arg = (*result_1).id;

										result_4 = iniciarjuego_1(&iniciarjuego_1_arg, clnt1);
										if (result_4 == (void *) NULL) {
											clnt_perror (clnt1, "call failed");
										}

										//enviar configuracion al servidor				
										result_7 = enviarconfiguracion_1(&enviarconfiguracion_1_arg, clnt1);
										if (result_7 == (bool_t *) NULL) {
											clnt_perror (clnt1, "call failed");
										}


									//Pregunta al servidor cada 10 segundos el estado de result_6.estado
									// 1 = empezar a jugar, salir del ciclo
									// 0 = esperar a otro jugador, seguir en el ciclo
										do{												
											result_6 = configuracion_1((void*)&configuracion_1_arg, clnt1);
											if (result_6 == (config_juego *) NULL) {
												clnt_perror (clnt1, "call failed");
											}
											if (result_6->estado == 1)
											{
												printf("\nEl juego ha iniciado\n");				
											}
											else
											{
												printf("\nEsperando a otro jugador....\n");
											}	
											sleep(10);									
										}while(result_6->estado == 0);
									}
									else
									{		
										
					                    iniciarjuego_1_arg = (*result_1).id;						
										result_4 = iniciarjuego_1(&iniciarjuego_1_arg, clnt1);
										if (result_4 == (void *) NULL) {
											clnt_perror (clnt1, "call failed");
										}

										//Validar si se repite color
										printf("\n¿Desea repetir color? 1:si / 0:no\n");
										scanf(" %d",&repetirColor2);
										
										printf("\n***** Repetir color: %d \n", repetirColor2);
										enviarconfirmacion_1_arg = repetirColor2;

										result_6->rol = 2;
										printf("\n***** Rol: %d \n", result_6->rol);

										result_12 = enviarconfirmacion_1(&enviarconfirmacion_1_arg, clnt1);
										if (result_12 == (void *) NULL) {
											clnt_perror (clnt1, "call failed");
										}																
									}
//--------------------------------------------- Empieza juego ---------------------------------------
								do
								{															
									if (result_6->rol == 1)
									{			
										// imprimir tablero									
										do{	
											
											system("clear");
											// imprimir tablero
											printf("\n----------------");
											printf(" Adivinar colores");
											printf(" -----------------");

											tablero(generacionColor,generacionEspiga);
											// pedir colores
											listaColores();

											int colorSeleccionado;
										
											printf("\nDigite el color 1: ");
											colorSeleccionado = obtenerNumeroValido(8);
											strcpy(enviarcolores_1_arg.color1,obtenerColor(colorSeleccionado));	

											printf("\nDigite el color 2: ");
											colorSeleccionado = obtenerNumeroValido(8);
											strcpy(enviarcolores_1_arg.color2,obtenerColor(colorSeleccionado));

											printf("\nDigite el color 3: ");
											colorSeleccionado = obtenerNumeroValido(8);
											strcpy(enviarcolores_1_arg.color3,obtenerColor(colorSeleccionado));

											printf("\nDigite el color 4: ");
											colorSeleccionado = obtenerNumeroValido(8);
											strcpy(enviarcolores_1_arg.color4,obtenerColor(colorSeleccionado));

											printf("\nDigite el color 5: ");
											colorSeleccionado = obtenerNumeroValido(8);
											strcpy(enviarcolores_1_arg.color5,obtenerColor(colorSeleccionado));

											//enviar colores al servidor
											result_7 = enviarcolores_1(&enviarcolores_1_arg, clnt1);
											if (result_7 == (bool_t *) NULL) {
												clnt_perror (clnt1, "call failed");
											}

											// pedir espigas
											do
											{
												result_10 = actualizartableroespiga_1(&actualizartableroespiga_1_arg, clnt1);
												if (result_10 == (info_espiga *) NULL) {
													clnt_perror (clnt1, "call failed");
												}
																						
												if (result_10->generacion == generacionEspiga)
												{
													printf("\nEsperando respuesta del rival...(M)\n");
												}
												else
												{
													printf("\nRespuesta del rival recibida...(M)\n");
												}
												sleep(10);
											} while (result_10->generacion == generacionEspiga);

											generacionEspiga++;
											generacionColor++;

											result_8 = actualizartablerocolor_1(&actualizartablerocolor_1_arg, clnt1);
											if (result_8 == (info_color *) NULL) {
												clnt_perror (clnt1, "call failed");
											}
											
											strcpy(color.color1, result_8->color1);
											strcpy(color.color2, result_8->color2);
											strcpy(color.color3, result_8->color3);
											strcpy(color.color4, result_8->color4);
											strcpy(color.color5, result_8->color5);
											strcpy(espiga.espiga1, result_10->espiga1);
											strcpy(espiga.espiga2, result_10->espiga2);
											strcpy(espiga.espiga3, result_10->espiga3);
											strcpy(espiga.espiga4, result_10->espiga4);
											strcpy(espiga.espiga5, result_10->espiga5);	

											tablero(generacionColor,generacionEspiga);

											//perdir estado del juego
											result_13 = estadojuego_1(&estadojuego_1_arg, clnt1);
											if (result_13 == (int *) NULL) {
												clnt_perror (clnt1, "call failed");
											}											
											//Cambiar rol
											if (*result_13 == 2)
											{
												result_6->rol = 2;
												generacionColor = 1;
												generacionEspiga = 0;
												reiniciar();
												partida++;
												enviarconfiguracion_1_arg.estado = 1;
												result_7 = enviarconfiguracion_1(&enviarconfiguracion_1_arg, clnt1);
												if (result_7 == (bool_t *) NULL) {
													clnt_perror (clnt1, "call failed");
												}
											}
											
										} while (generacionColor < 10 && *result_13 != 2);

//---------------------------------------------------------------------------------------------------
									}else{ // Rol Espigas
										//Enviar colores que se van a adivinar
										system("clear");
										printf("\n----------------");
										printf(" Enviar colores para que el rival adivine");
										printf(" -----------------\n");
										listaColores();
										int colorSeleccionado;
										
										printf("\nDigite el color 1: ");
										colorSeleccionado = obtenerNumeroValido(8);
										strcpy(enviarcolores_1_arg.color1,obtenerColor(colorSeleccionado));	

										printf("\nDigite el color 2: ");
										colorSeleccionado = obtenerNumeroValido(8);
										strcpy(enviarcolores_1_arg.color2,obtenerColor(colorSeleccionado));

										printf("\nDigite el color 3: ");
										colorSeleccionado = obtenerNumeroValido(8);
										strcpy(enviarcolores_1_arg.color3,obtenerColor(colorSeleccionado));

										printf("\nDigite el color 4: ");
										colorSeleccionado = obtenerNumeroValido(8);
										strcpy(enviarcolores_1_arg.color4,obtenerColor(colorSeleccionado));

										printf("\nDigite el color 5: ");
										colorSeleccionado = obtenerNumeroValido(8);
										strcpy(enviarcolores_1_arg.color5,obtenerColor(colorSeleccionado));

										//guardar solucion en la estructura solucion
										strcpy(solucion.color1,enviarcolores_1_arg.color1);
										strcpy(solucion.color2,enviarcolores_1_arg.color2);
										strcpy(solucion.color3,enviarcolores_1_arg.color3);
										strcpy(solucion.color4,enviarcolores_1_arg.color4);
										strcpy(solucion.color5,enviarcolores_1_arg.color5);

										//enviar colores al servidor
										result_7 = enviarcolores_1(&enviarcolores_1_arg, clnt1);
										if (result_7 == (bool_t *) NULL) {
											clnt_perror (clnt1, "call failed");
										}		

										do
										{
											// Esperar respuesta del jugador 1, hacer petición cada 10 segundos
											do
											{
												if (partida == 2)
												{
													printf("\nEl juego ha terminado\n");
													break;
												}											

												result_8 = actualizartablerocolor_1(&actualizartablerocolor_1_arg, clnt1);
												if (result_8 == (info_color *) NULL) {
													clnt_perror (clnt1, "call failed");
												}
																						
												if (result_8->generacion != generacionColor)
												{
													printf("\nEsperando respuesta del rival...(E)\n");
												}
												else
												{
													printf("\nRespuesta del rival recibida...(E)\n");
												}
												sleep(10);
											} while (result_8->generacion != generacionColor);
											// imprimir tablero
											generacionColor++;

											result_10 = actualizartableroespiga_1(&actualizartableroespiga_1_arg, clnt1);
											if (result_10 == (info_espiga *) NULL) {
												clnt_perror (clnt1, "call failed");
											}

											strcpy(color.color1, result_8->color1);
											strcpy(color.color2, result_8->color2);
											strcpy(color.color3, result_8->color3);
											strcpy(color.color4, result_8->color4);
											strcpy(color.color5, result_8->color5);

											tablero(generacionColor,generacionEspiga);
											escudo();

											// Pedir espigas

											int espigaSeleccionada;
											printf("\n1: Negra | 2: Blanca | 3: Ninguno\n");

											printf("\nDigite el color de la espiga 1: ");
											espigaSeleccionada = obtenerNumeroValido(3);
											strcpy(enviarespigas_1_arg.espiga1,obtenerEspiga(espigaSeleccionada));

											printf("\nDigite el color de la espiga 2: ");
											espigaSeleccionada = obtenerNumeroValido(3);
											strcpy(enviarespigas_1_arg.espiga2,obtenerEspiga(espigaSeleccionada));

											printf("\nDigite el color de la espiga 3: ");
											espigaSeleccionada = obtenerNumeroValido(3);
											strcpy(enviarespigas_1_arg.espiga3,obtenerEspiga(espigaSeleccionada));

											printf("\nDigite el color de la espiga 4: ");
											espigaSeleccionada = obtenerNumeroValido(3);
											strcpy(enviarespigas_1_arg.espiga4,obtenerEspiga(espigaSeleccionada));

											printf("\nDigite el color de la espiga 5: ");
											espigaSeleccionada = obtenerNumeroValido(3);
											strcpy(enviarespigas_1_arg.espiga5,obtenerEspiga(espigaSeleccionada));

											//enviar espigas al servidor
											result_9 = enviarespigas_1(&enviarespigas_1_arg, clnt1);
											if (result_9 == (bool_t *) NULL) {
												clnt_perror (clnt1, "call failed");
											}

											generacionEspiga++;
											result_10 = actualizartableroespiga_1(&actualizartableroespiga_1_arg, clnt1);
											if (result_10 == (info_espiga *) NULL) {
												clnt_perror (clnt1, "call failed");
											}

											system("clear");
											strcpy(espiga.espiga1, result_10->espiga1);
											strcpy(espiga.espiga2, result_10->espiga2);
											strcpy(espiga.espiga3, result_10->espiga3);
											strcpy(espiga.espiga4, result_10->espiga4);
											strcpy(espiga.espiga5, result_10->espiga5);																			
											tablero(generacionColor,generacionEspiga);
											escudo();

											//perdir estado del juego
											result_13 = estadojuego_1(&estadojuego_1_arg, clnt1);
											if (result_13 == (int *) NULL) {
												clnt_perror (clnt1, "call failed");
											}	
											//Cambiar rol
											if (*result_13 == 2)
											{
												result_6->rol = 1;
												generacionColor = 1;
												generacionEspiga = 0;
												reiniciar();
												partida++;
											}										

										} while (generacionEspiga < 10 && *result_13 != 2);


									}

								} while (partida != 2);
								//fin del juego
								printf("\n----------------");
								printf(" Fin del juego");
								printf(" -----------------\n");
								
								result_11 = puntuacion_1(&puntuacion_1_arg, clnt1);
								if (result_11 == (fin_juego *) NULL) {
									clnt_perror (clnt1, "call failed");
								}
								
								//Imprimir resultado
								printf("\n================ Resultado ==================");
								printf("\nPartida: %d", result_11->id_partida);
								printf("\nGanador: %d", result_11->id_ganador);
								printf("\nPuntaje jugador 1: %d", result_11->puntaje1);
								printf("\nPuntaje jugador 2: %d", result_11->puntaje2);
								printf("\n==============================================");
	
									break;
								case 2:
									printf("\n----------------");
									printf(" Consultar registro");
									printf(" -----------------\n");


									consulta_1_arg = (*result_1).id;
									result_14 = consulta_1(&consulta_1_arg, clnt1);
							
									if (result_14 == (data_juego *) NULL) {
										clnt_perror (clnt1, "call failed");
									}
									if ((*result_14).id_juego== -1) 
									{	
											printf("\nRegistro NO encontrado\n");
									}
									else{
										printf("\n================ Registro ==================");
										printf("\nPartida: %d", result_14->id_juego);
										printf("\nJugador 1: %d", result_14->id_jugador1);
										printf("\nJugador 2: %d", result_14->id_jugador2);
										printf("\nGanador: %d", result_14->ganador);
										printf("\nFecha: %s", result_14->fecha);
										printf("\n============================================");
									}
									break;
								case 3:
									exit(2);
									break;
							
								default:
									printf("Opcion invalida\n");
									break;				
							}
						}while(opcion < 3);
					
					}
					else{
						do{
							printf("\n================ Menu Admin ==================");
							printf("\n 1. Registrar Usuario ");
							printf("\n 2. Consultar Usuario ");
							printf("\n 3. Salir ");
							printf("\n=======================================");
							printf("\n Digite opcion: ");
							scanf("%d",&opcion2);
							switch(opcion2)
							{    
								case 1:
									printf("\n------------------");
									printf(" Registrar usuario");
									printf(" -------------------\n");


									printf("Digite el numero de identificacion: ");
									scanf("%d",&registrarusuarios_1_arg.id);
									printf("Digite el nombre completo: ");
									scanf("%s",&registrarusuarios_1_arg.nombreCompleto);
									printf("Digite la edad: ");				
									scanf("%d", &registrarusuarios_1_arg.edad);
									printf("Digite el nombre de usuario: ");
									scanf("%s", &registrarusuarios_1_arg.usuario);
									printf("Digite la clave: ");
									scanf("%s", &registrarusuarios_1_arg.clave);
						
									result_2=registrarusuarios_1(&registrarusuarios_1_arg,clnt);
									if(result_2 == (bool_t *)NULL)
									{
									clnt_perror(clnt,"call failed");
									}
									else if(*result_2==TRUE)
									{
										printf("Usuario registrado exitosamente\n");
									}
									else
									{
										printf("\nUsuario NO registrado. se alcanzó la cantidad maxima de usuarios a registra");
									}
									break;

								case 2:
									printf("\n------------------");
									printf(" Consultar usuario");
									printf(" -------------------\n");
									printf("\nDigite el id del usuario a consultar: ");
									scanf("%d",&consultarusuario_1_arg);
									result_3=consultarusuario_1(&consultarusuario_1_arg,clnt);

									if (result_3 == (datos_usuario *) NULL) {
										clnt_perror (clnt, "call failed");
									}
									else if ((*result_3).id == -1) 
									{	
									printf("\nUsuario NO encontrado\n");
									}
									else
									{
										printf("\n================ Usuario ==================");
										printf("\nIdentificacion: %d", result_3 -> id);
										printf("\nNombre completo: %s", result_3->nombreCompleto);
										printf("\nUsuario: %s", result_3->usuario);
										printf("\n===========================================");
									}
									break;

								case 3:
									exit(2);
									break;
							
								default:
									printf("Opcion invalida\n");
									break;				
							}
						}while(opcion < 3);

					}
										
				}
				break;

			case 2:
				exit(1);
				break;
		
			default:
				printf("Opcion invalida\n");
				break;				
		}
	}while(opcion < 2);


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void listaColores(){
	printf("\n-----------------------------------------\n");
	printf(" Lista de colores");
	printf("\n ------------------------------------------------");
	printf("\n1. Rojo      3. Beis     5. Cian     7. Lila");
	printf("\n2. Azul      4. Rosa     6. Mora     8. Jade");
	printf("\n ------------------------------------------------\n");

}


char* obtenerColor(int numero) {
    switch(numero) {
        case 1:
            return "Rojo";
        case 2:
            return "Azul";
        case 3:
            return "Beis";
        case 4:
            return "Rosa";
        case 5:
            return "Cian";
        case 6:
            return "Mora";
        case 7:
            return "Lila";
        case 8:
            return "Jade";
        default:
            return "Azul";
    }
}

char* obtenerEspiga(int numero){
	switch(numero){
		case 1:
			return "N";
		case 2:
			return "B";
		case 3:
			return "X";
		default:
			return "";
	}
}


// Función que solicita un número en el rango de 1 a 8 y lo retorna
int obtenerNumeroValido(int rango) {
    int numero;
    do {
        printf("Ingresa un número del 1 al %d: ",rango);
        scanf("%d", &numero);
    } while (numero < 1 || numero > rango);
    
    return numero;
}


void tablero(int generacionColor, int generacionEspiga){

	//colocamos los colores en las primeras 5 columnas
	strcpy(matriz[generacionColor-1][0],color.color1);
	strcpy(matriz[generacionColor-1][1],color.color2);
	strcpy(matriz[generacionColor-1][2],color.color3);
	strcpy(matriz[generacionColor-1][3],color.color4);
	strcpy(matriz[generacionColor-1][4],color.color5);

	//colocamos las espigas en las ultimas 5 columnas
	strcpy(matriz[generacionEspiga][5],espiga.espiga1);
	strcpy(matriz[generacionEspiga][6],espiga.espiga2);
	strcpy(matriz[generacionEspiga][7],espiga.espiga3);
	strcpy(matriz[generacionEspiga][8],espiga.espiga4);
	strcpy(matriz[generacionEspiga][9],espiga.espiga5);

	
	//imprimimos el tablero donde no hay nada colocamos x
	printf("\n");
	printf("----------------------------------------------------------------------------------------------------\n");
	printf("  | color1 | color2 | color3 | color4 | color5 |  1  |  2  |  3  |  4  |  5  |\n");
	printf("----------------------------------------------------------------------------------------------------\n");
	for (int i = 0; i < 10; i++)
	{
		printf("  |");
		for (int j = 0; j < 10; j++)
		{
			if (strcmp(matriz[i][j],"") == 0)
			{
				printf(" ");
			}else{
				printf("  %s  |",matriz[i][j]);
			}
		}
		printf("\n");
	}
}

void escudo(){
	// imprimir la estructura solucion
	printf("\n ****************************************************************************");
	printf("\n      %s  %s  %s  %s  %s ",solucion.color1,solucion.color2,solucion.color3,solucion.color4,solucion.color5);
	printf("\n ****************************************************************************\n");
}

void reiniciar(){
	//Matriz de colores y espigas
	for (int i = 0; i < 10; i++)
	{
		for (int j = 0; j < 10 ; j++)
		{
			strcpy(matriz[i][j],"");
		}
	}
	printf("\n*********************************\n");
	printf("\n          Ronda termina          \n");
	printf("\n*********************************\n");
	//Reinicio de variables y estructuras para la siguiente ronda
	strcpy(color.color1,"");
	strcpy(color.color2,"");
	strcpy(color.color3,"");
	strcpy(color.color4,"");
	strcpy(color.color5,"");
	strcpy(espiga.espiga1,"");
	strcpy(espiga.espiga2,"");
	strcpy(espiga.espiga3,"");
	strcpy(espiga.espiga4,"");
	strcpy(espiga.espiga5,"");
	strcpy(solucion.color1,"");
	strcpy(solucion.color2,"");
	strcpy(solucion.color3,"");
	strcpy(solucion.color4,"");
	strcpy(solucion.color5,"");
	
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
exit (0);
}
