/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionUsuarios.h"
#include "gestionJuego.h"

void gestion_usuarios_1(char *host)
{
	CLIENT *clnt;
	datos_usuario  *result_1;
	datos_sesion  abrirsesion_1_arg;
	bool_t  *result_2;
	datos_usuario  registrarusuarios_1_arg;
	datos_usuario  *result_3;
	int  consultarusuario_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_usuarios, gestion_usuarios_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int opcion3;
	int opcion2;
	int opcion;
	do
	{
		printf("\n================ Menu sesion ==================");
		printf("\n 1. Iniciar sesion ");
		printf("\n 2. Salir ");
		printf("\n=======================================");
		printf("\n Digite opcion: ");
		scanf("%d",&opcion);
		switch(opcion)
		{    
			case 1:
				printf("\n----------------");
				printf(" Iniciar sesion");
				printf(" -----------------\n");

				printf("Digite el numero de identificacion: ");
				scanf("%d",&abrirsesion_1_arg.id);
				printf("Digite su usuario: ");
				scanf("%s", &abrirsesion_1_arg.usuario);
				printf("Digite su clave: ");
				scanf("%s", &abrirsesion_1_arg.clave);

				result_1=abrirsesion_1(&abrirsesion_1_arg,clnt);
				if ((*result_1).id == -1) {
					printf("\nUsuario NO encontrado");
				}
				else{

					if ((*result_1).id > 0)
					{
						CLIENT *clnt1;
							void  *result_4;
							int  iniciarjuego_1_arg;

						#ifndef	DEBUG
							clnt1 = clnt_create (host, gestion_juego, gestion_juego_version, "udp");
							if (clnt1 == NULL) {
								clnt_pcreateerror (host);
								exit (1);
							}
						#endif	/* DEBUG */

						do{

							printf("\n================ Menu Jugador ==================");
							printf("\n 1. jugar");
							printf("\n 2. consultar");
							printf("\n 3. Salir ");
							printf("\n================================================");
							printf("\n Digite opcion: ");
							scanf("%d",&opcion3);
							switch(opcion3)
							{    
								case 1:
									printf("\n----------------");
									printf(" Jugar");
									printf(" -----------------\n");

									iniciarjuego_1_arg = (*result_1).id;
							
									result_4 = iniciarjuego_1(&iniciarjuego_1_arg, clnt1);
									if (result_4 == (void *) NULL) {
										clnt_perror (clnt1, "call failed");
									}

									printf("Se ha iniciado el juego\n");
									break;

								case 2:
									printf("\n----------------");
									printf(" Consultar");
									printf(" -----------------\n");
									printf("\nEn construcion..\n");
									break;

								case 3:
									exit(2);
									break;
							
								default:
									printf("Opcion invalida\n");
									break;				
							}
						}while(opcion < 3);

					}
					else{
						do{
							printf("\n================ Menu Admin ==================");
							printf("\n 1. Registrar Usuario ");
							printf("\n 2. Consultar Usuario ");
							printf("\n 3. Salir ");
							printf("\n=======================================");
							printf("\n Digite opcion: ");
							scanf("%d",&opcion2);
							switch(opcion2)
							{    
								case 1:
									printf("\n------------------");
									printf(" Registrar usuario");
									printf(" -------------------\n");

									printf("Digite el numero de identificacion: ");
									scanf("%d",&registrarusuarios_1_arg.id);
									printf("Digite el nombre completo: ");
									scanf("%s",&registrarusuarios_1_arg.nombreCompleto);
									printf("Digite la edad: ");				
									scanf("%d", &registrarusuarios_1_arg.edad);
									printf("Digite el nombre de usuario: ");
									scanf("%s", &registrarusuarios_1_arg.usuario);
									printf("Digite la clave: ");
									scanf("%s", &registrarusuarios_1_arg.clave);
						
									result_2=registrarusuarios_1(&registrarusuarios_1_arg,clnt);
									if(result_2 == (bool_t *)NULL)
									{
									clnt_perror(clnt,"call failed");
									}
									else if(*result_2==TRUE)
									{
										printf("Usuario registrado exitosamente\n");
									}
									else
									{
										printf("\nUsuario NO registrado. se alcanzó la cantidad maxima de usuarios a registra");
									}
									break;

								case 2:
									printf("\n------------------");
									printf(" Consultar usuario");
									printf(" -------------------\n");
									printf("\nDigite el id del usuario a consultar: ");
									scanf("%d",&consultarusuario_1_arg);
									result_3=consultarusuario_1(&consultarusuario_1_arg,clnt);

									if (result_3 == (datos_usuario *) NULL) {
										clnt_perror (clnt, "call failed");
									}
									else if ((*result_3).id == -1) 
									{	
									printf("\nUsuario NO encontrado\n");
									}
									else
									{
										printf("\n================ Usuario ==================");
										printf("\nIdentificacion: %d", result_3->id);
										printf("\nNombre completo: %s", result_3->nombreCompleto);
										printf("\nUsuario: %s", result_3->usuario);
										printf("\n===========================================");
									}
									break;

								case 3:
									exit(2);
									break;
							
								default:
									printf("Opcion invalida\n");
									break;				
							}
						}while(opcion < 3);

					}
										
				}
				break;

			case 2:
				exit(1);
				break;
		
			default:
				printf("Opcion invalida\n");
				break;				
		}
	}while(opcion < 2);


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_usuarios_1 (host);
    exit (0);
}
