/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONJUEGO_H_RPCGEN
#define _GESTIONJUEGO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define gestion_juego 0x30000014
#define gestion_juego_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define iniciarJuego 1
extern  void * iniciarjuego_1(int *, CLIENT *);
extern  void * iniciarjuego_1_svc(int *, struct svc_req *);
extern int gestion_juego_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define iniciarJuego 1
extern  void * iniciarjuego_1();
extern  void * iniciarjuego_1_svc();
extern int gestion_juego_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONJUEGO_H_RPCGEN */
