/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MULTIOPERACIONES_H_RPCGEN
#define _MULTIOPERACIONES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30

struct numbers {
	float a;
	float b;
};
typedef struct numbers numbers;

struct nodo_multioperaciones {
	char estado[MAXNOM];
	char resultado[MAXNOM];
};
typedef struct nodo_multioperaciones nodo_multioperaciones;

#define multioperaciones 0x20000001
#define multioperaciones_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define operar 1
extern  nodo_multioperaciones * operar_1(numbers *, CLIENT *);
extern  nodo_multioperaciones * operar_1_svc(numbers *, struct svc_req *);
extern int multioperaciones_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define operar 1
extern  nodo_multioperaciones * operar_1();
extern  nodo_multioperaciones * operar_1_svc();
extern int multioperaciones_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);
extern  bool_t xdr_nodo_multioperaciones (XDR *, nodo_multioperaciones*);

#else /* K&R C */
extern bool_t xdr_numbers ();
extern bool_t xdr_nodo_multioperaciones ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MULTIOPERACIONES_H_RPCGEN */
