/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "multioperaciones.h"
#include "division.h"

nodo_multioperaciones *
operar_1_svc(numbers *argp, struct svc_req *rqstp)
{
	CLIENT *clnt;
	float  *result_1;
	numbers  operar_division_1_arg;	
	float suma, resta, multiplicacion;
	char divisionStr[20], sumaStr[10], restaStr[10], multiplicacionStr[10];
	

	static nodo_multioperaciones  result;

#ifndef	DEBUG

	char *host="localhost";
	clnt = clnt_create (host, division, division_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	strcpy(result.estado, "OK");
	suma = argp->a + argp->b;
	resta = argp->a - argp->b;
	multiplicacion = argp->a * argp->b;
	snprintf(sumaStr, sizeof(sumaStr), "%2f", suma);
	snprintf(restaStr, sizeof(restaStr), "%2f", resta);
	snprintf(multiplicacionStr, sizeof(multiplicacionStr), "%2f", multiplicacion);

	//Concatenar los resultados
	strcat(result.resultado, "S: ");
	strcat(result.resultado, sumaStr);
	strcat(result.resultado, " R: ");
	strcat(result.resultado, restaStr);
	strcat(result.resultado, " M: ");
	strcat(result.resultado, multiplicacionStr);

	if (argp->b != 0)
	{	
		printf("Division\n");
		result_1 = operar_division_1(&operar_division_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			snprintf(divisionStr, sizeof(divisionStr), "%2f", *result_1);	
			strcat(result.resultado, " D: ");
			strcat(result.resultado, divisionStr);		
		}	
	}
	else
	{
		strcpy(result.estado, "Error");
		printf("No se puede dividir por cero\n");
	}
	
	return &result;
}
