/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GESTIONANTEPROYECTOS_H_RPCGEN
#define _GESTIONANTEPROYECTOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXFECHA 10

struct nodo_anteproyecto {
	char titulo[MAXNOM];
	char estudiante[MAXNOM];
	char director[MAXNOM];
	char fechaPresentacion[MAXFECHA];
	int codigo;
};
typedef struct nodo_anteproyecto nodo_anteproyecto;

#define gestion_anteproyectos 0x20000001
#define gestion_anteproyectos_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrarAnteproyectoSistema 1
extern  bool_t * registraranteproyectosistema_1(nodo_anteproyecto *, CLIENT *);
extern  bool_t * registraranteproyectosistema_1_svc(nodo_anteproyecto *, struct svc_req *);
#define consultarAnteproyecto 2
extern  nodo_anteproyecto * consultaranteproyecto_1(char **, CLIENT *);
extern  nodo_anteproyecto * consultaranteproyecto_1_svc(char **, struct svc_req *);
extern int gestion_anteproyectos_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarAnteproyectoSistema 1
extern  bool_t * registraranteproyectosistema_1();
extern  bool_t * registraranteproyectosistema_1_svc();
#define consultarAnteproyecto 2
extern  nodo_anteproyecto * consultaranteproyecto_1();
extern  nodo_anteproyecto * consultaranteproyecto_1_svc();
extern int gestion_anteproyectos_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_anteproyecto (XDR *, nodo_anteproyecto*);

#else /* K&R C */
extern bool_t xdr_nodo_anteproyecto ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GESTIONANTEPROYECTOS_H_RPCGEN */
