/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REGISTROJUEGO_H_RPCGEN
#define _REGISTROJUEGO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30
#define MAXDAT 12

struct datos_juego {
	int id_juego;
	int id_jugador1;
	int id_jugador2;
};
typedef struct datos_juego datos_juego;

#define registro_juego 0x30000015
#define registro_juego_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define enviarNotificacion 1
extern  void * enviarnotificacion_1(struct datos_juego *, CLIENT *);
extern  void * enviarnotificacion_1_svc(struct datos_juego *, struct svc_req *);
extern int registro_juego_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarNotificacion 1
extern  void * enviarnotificacion_1();
extern  void * enviarnotificacion_1_svc();
extern int registro_juego_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos_juego (XDR *, datos_juego*);

#else /* K&R C */
extern bool_t xdr_datos_juego ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REGISTROJUEGO_H_RPCGEN */
