/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "registroJuego.h"

void *
enviarnotificacion_1_svc(struct datos_juego *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("*** hay 2 jugadores, se inicia el juego ***\n");

	return (void *) &result;
}
