/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "registroJuego.h"

void *
enviarnotificacion_1_svc(struct datos_juego *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("\n*** Informacion ***\n");
	printf("\n Id juego:%d\n", argp->id_juego);
	printf("\n Jugador 1%d\n", argp->id_jugador1);
	printf("\n Jugador 2%d\n", argp->id_jugador2);


	return (void *) &result;
}
